<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>User Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
        }
        h1 {
            margin-bottom: 10px;
        }
        h2 {
            margin-top: 25px;
            margin-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 6px;
        }
        th {
            background: #f2f2f2;
            text-align: left;
        }
        .status-active { color: green; }
        .status-pending { color: orange; }
        .status-inactive { color: red; }
    </style>
</head>
<body>

    <h1>User Report</h1>

    <p>
        Generated: {{ now()->format('Y-m-d H:i') }}<br>
        Generated by: {{ $user->name ?? '' }}
    </p>

    <h2>Profile</h2>
    <table>
        <tr>
            <th>ID</th>
            <td>{{ $user->id }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ $user->name }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ $user->email }}</td>
        </tr>
        <tr>
            <th>Role</th>
            <td>{{ $user->role->name ?? '-' }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td class="status-{{ $user->status }}">{{ ucfirst($user->status) }}</td>
        </tr>
        <tr>
            <th>Online</th>
            <td>{{ $user->is_online ? 'Yes' : 'No' }}</td>
        </tr>
        <tr>
            <th>Created At</th>
            <td>{{ $user->created_at }}</td>
        </tr>
    </table>

    <h2>Statistics</h2>
    <table>
        <tr>
            <th>Documents</th>
            <td>{{ $user->documents_count ?? 0 }}</td>
        </tr>
        <tr>
            <th>Chat Sessions</th>
            <td>{{ $user->sessions_chat_count ?? 0 }}</td>
        </tr>
    </table>

    <h2>Owner Statistics</h2>
    <table>
        <tr>
            <th>Team Documents</th>
            <td>{{ $user->documents_team_count ?? 0 }}</td>
        </tr>
        <tr>
            <th>Team Chat Sessions</th>
            <td>{{ $user->sessions_team_chat_count ?? 0 }}</td>
        </tr>
        <tr>
            <th>Client Users</th>
            <td>{{ $user->client_users_count ?? 0 }}</td>
        </tr>
        <tr>
            <th>Total Revenue (30 days)</th>
            <td>{{ $user->economist_30_last['total_revenue'] ?? 0 }}</td>
        </tr>

        <tr>
            <th>Total AI Cost (30 days)</th>
            <td>{{ $user->economist_30_last['total_ai_cost'] ?? 0 }}</td>
        </tr>

        <tr>
            <th>Net Margin (%)</th>
            <td>{{ $user->economist_30_last['net_margin'] ?? 0 }}%</td>
        </tr>
        <tr>
            <th>Active Users Last 30 Days</th>
            <td>{{ $user->active_users_last_30_days ?? 0 }}</td>
        </tr>
        <tr>
            <th>Deleted Users Last 30 Days</th>
            <td>{{ $user->deleted_users_last_30_days ?? 0 }}</td>
        </tr>
    </table>

    <h2>Subscription</h2>
    <table>
        <tr>
            <th>Plan</th>
            <td>{{ $user->subscription->plan->name ?? '-' }}</td>
        </tr>
        <tr>
            <th>Price</th>
            <td>{{ $user->subscription->planPrice->price ?? '-' }}</td>
        </tr>
    </table>

    <h2>Payments</h2>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($user->payments ?? [] as $payment)
            <tr>
                <td>{{ $payment->id }}</td>
                <td>{{ $payment->amount ?? '-' }}</td>
                <td>{{ $payment->status ?? '-' }}</td>
                <td>{{ $payment->created_at }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

</body>
</html>